import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {safePath,namesFor,validatePreparation,portable,base,exactRuntimeInventory,bundleProfile} from './portable.mjs';
import {runtimePaths} from './build.mjs';
import {operator} from './pilot-install.mjs';
import {candidate,digest,makePlan,validatePlan,revalidate,assertOwned} from './pilot-plan.mjs';
const now=1790456400000;
test('user bundle has a distinct exact inventory without altering older profiles',()=>{
 assert.equal(bundleProfile('portable-enrolled-user-pilot-1'),'enrolled-user-v1');
 const user=runtimePaths('enrolled-user-v1'),role=runtimePaths('enrolled-role-v1');
 assert.equal(user.length,45);assert.equal(role.length,41);
 assert.deepEqual(user.filter(p=>!role.includes(p)),['UserApi','UserExecution','UserRecovery','UserTransport'].map(n=>'classes/IrisOps.Guard.'+n+'.cls'));
 assert.throws(()=>exactRuntimeInventory(role,user));
 assert.throws(()=>exactRuntimeInventory([...user,'classes/IrisOps.Guard.UserTestExecution.cls'],user));
});
test('portable versions select explicit inventories, never caller-supplied counts',()=>{assert.equal(bundleProfile('portable-pilot-1'),'fixed-targets-v1');assert.equal(bundleProfile('portable-enrolled-pilot-1'),'enrolled-targets-v1');assert.equal(bundleProfile('portable-enrolled-role-pilot-1'),'enrolled-role-v1');assert.equal(runtimePaths('fixed-targets-v1').length,36);assert.equal(runtimePaths('enrolled-targets-v1').length,37);assert.equal(runtimePaths('enrolled-role-v1').length,41);for(const v of ['',null,'portable-enrolled-pilot-2','__proto__',{},37])assert.throws(()=>bundleProfile(v));assert.throws(()=>runtimePaths('unknown'));});
test('enrolled inventory rejects substituted policy, extra tests and old fixed-target runtime',()=>{const paths=runtimePaths('enrolled-targets-v1'),policy='classes/IrisOps.Guard.TargetPolicy.cls';assert.ok(paths.includes(policy));for(const bad of [runtimePaths('fixed-targets-v1'),paths.map(p=>p===policy?'classes/IrisOps.Guard.TestTargetPolicy.cls':p),[...paths,'ui/secret.json'],paths.map(p=>p.endsWith('client.js')?p+'.bak':p)])assert.throws(()=>exactRuntimeInventory(bad,paths));});
test('unknown installer runtime profile fails before any Docker call',()=>{let calls=0;assert.throws(()=>operator({run:()=>calls++,runtimeProfile:'unbounded'}));assert.equal(calls,0);});
const prep=()=>{const body={schema:1,action:'BUILD_AND_CREATE_NEW_LAB_TLS',resources:namesFor('irisops-pilot-unit'),daemonId:'test',bundleHash:'a'.repeat(64),nonce:'b'.repeat(32),createdAt:now};return {...body,fingerprint:digest(body)};};
test('portable paths reject traversal, absolute paths, empty segments and Windows escapes',()=>{for(const p of ['../x','/x','a/../b','C:/x','a\\b','a//b','./x','a/./b','a\n','a:stream'])assert.throws(()=>safePath(p));assert.equal(safePath('runtime/classes/IrisOps.Guard.Api.cls'),'runtime/classes/IrisOps.Guard.Api.cls');});
test('portable build inventory rejects extra test classes, missing files and duplicates',()=>{const expected=['Dockerfile','manifest.json','classes/Runtime.cls'];exactRuntimeInventory([...expected].reverse(),expected);for(const actual of [[...expected,'classes/UnexpectedTest.cls'],expected.slice(1),[...expected,'Dockerfile']])assert.throws(()=>exactRuntimeInventory(actual,expected));});
test('portable resource names stay in the isolated namespace',()=>{assert.deepEqual(namesFor('irisops-pilot-unit'),{name:'irisops-pilot-unit',certificateVolume:'irisops-guard-unit-cert-private',helper:'irisops-pilot-unit-tls-init'});for(const n of ['original','irisops-pilot-','irisops-pilot-a;bad','irisops-pilot-a/b'])assert.throws(()=>namesFor(n));});
test('portable preparation needs exact confirmation and fresh plan',()=>{const p=prep();validatePreparation(p,p.fingerprint,now);for(const key of ['wrong','',undefined])assert.throws(()=>validatePreparation(p,key,now));assert.throws(()=>validatePreparation(p,p.fingerprint,now+900000));assert.throws(()=>validatePreparation(p,p.fingerprint,now-30001));});
test('portable preparation rejects changed identity and rehashed unknown action',()=>{const p=prep();assert.throws(()=>validatePreparation({...p,daemonId:'changed'},p.fingerprint,now));const {fingerprint,...body}=p;body.action='DELETE';assert.throws(()=>validatePreparation({...body,fingerprint:digest(body)},digest(body),now));});
test('portable unconfirmed prepare never invokes Docker or filesystem',async()=>{let calls=0;const api=portable({run:()=>{calls++;throw Error('Unexpected Docker access');}});await assert.rejects(api.prepare(prep(),'wrong','never-create-portable.json'));assert.equal(calls,0);});
test('portable altered preparation receipt rejected before Docker',async()=>{let calls=0;const api=portable({run:()=>{calls++;throw Error('Unexpected Docker access');}});await assert.rejects(api.installedOperator({schema:1,complete:true,fingerprint:'bad'}));assert.equal(calls,0);});
test('portable target supports rebuilt immutable image without relaxing plan binding',()=>{const target={image:'sha256:'+'d'.repeat(64),packageHash:'e'.repeat(64)},config={name:'irisops-pilot-unit',port:52807,certificateVolume:'irisops-guard-unit-cert-private'},snapshot={daemonId:'d',imageId:target.image,packageHash:target.packageHash,certificate:{Name:config.certificateVolume,Driver:'local',Scope:'local',CreatedAt:'2026-09-26T18:00:00Z'},containerAbsent:true,dataAbsent:true,portAvailable:true};const p=makePlan(config,snapshot,{now,nonce:'a'.repeat(32),target});validatePlan(p,p.fingerprint,{now,target});revalidate(p,snapshot,target);assert.throws(()=>validatePlan(p,p.fingerprint,{now}));assert.throws(()=>revalidate(p,{...snapshot,imageId:candidate.image},target));assert.throws(()=>makePlan(config,snapshot,{now,nonce:'a'.repeat(32),target:{image:'floating:tag',packageHash:target.packageHash}}));});
test('portable built-image ownership cannot substitute a different image',()=>{const target={image:'sha256:'+'d'.repeat(64),packageHash:'e'.repeat(64)},p={nonce:'a'.repeat(32),config:{name:'irisops-pilot-unit',port:52807,certificateVolume:'irisops-guard-unit-cert-private'}},id='f'.repeat(64),c={Id:id,Name:'/'+p.config.name,Image:target.image,Config:{Labels:{'irisops.pilot.owner':p.nonce},Env:['ISC_DATA_DIRECTORY=/durable/iris']},HostConfig:{Privileged:false,NetworkMode:'bridge',PortBindings:{'52774/tcp':[{HostIp:'127.0.0.1',HostPort:'52807'}]}},Mounts:[{Type:'volume',Name:p.config.name+'-data',Destination:'/durable',RW:true},{Type:'volume',Name:p.config.certificateVolume,Destination:'/run/irisops-tls',RW:false}]};assertOwned(c,p,id,target);assert.throws(()=>assertOwned({...c,Image:candidate.image},p,id,target));});
test('portable source generator uses immutable base and an explicit file allowlist',async()=>{assert.match(base,/@sha256:[a-f0-9]{64}$/);const src=await readFile(new URL('build-portable.mjs',import.meta.url),'utf8');assert.ok(src.includes('reference.contentSha256,candidate.packageHash'));assert.ok(src.includes("['portable.mjs','pilot-install.mjs','pilot-plan.mjs','build.mjs']"));assert.ok(!src.includes('readdir'));});
test('historical portable guide and runner retain their recorded fixed targets without external checkout files',async()=>{
 const guide=await readFile(new URL('portable-operator-guide.md',import.meta.url),'utf8'),runner=await readFile(new URL('verify-portable-live.mjs',import.meta.url),'utf8');
 // This is a source consistency check, not a revalidation of the old archive.
 // Native historical evidence remains bound to its published validation hash.
 for(const target of ['IrisOps_GuardProbeWallet','/csp/irisops-guard-testweb']){assert.ok(guide.includes(target));assert.ok(runner.includes(target));}
});
